### PR TITLE
Revert "Revert "[FIX] sale_coupon_advanced_delivery: init (#24)""

### PR DESCRIPTION
**Pull request by oerp-odoo**
This reverts commit 53df326372ea337c4ada90cbe41a58a78f8b9950.

### CODE REVIEW

**Review by jcoux — CHANGES_REQUESTED** [review]
Review will arrive.

**Review by jcoux — CHANGES_REQUESTED** [review]
We have a problem here, because we don't ignore delivery lines when we recompute coupon lines.
We re-compute entirely the delivery line from the carrier.
The problem is by example: if you update the price unit of the delivery line of the sale order, when you re-compute the delivery line, the custom price will be lost.

The original problem of this provides from the module `sale_coupon_advanced` which implied this new behavior for all sale order lines.
With code core only, if you change the price unit of a sale order line, the custom price unit is kept even if you recompute coupon lines.
With `sale_coupon_advanced`, it's not the case.
That's why you must do this bridge.

Finally, for our needs, it's ok like you did, but it's a deep change of the original behavior.

Please add in the readme of the module `sale_coupon_advanced` that it's a limitation of the module which implied to lost custom price unit when we recompute coupon lines.

And please add in the readme of the module `sale_coupon_advanced_delivery` that the delivery line will be re-compute each time we recompute coupon lines.

**Comment by oerp-odoo** [comment]
> We have a problem here, because we don't ignore delivery lines when we recompute coupon lines.
> We re-compute entirely the delivery line from the carrier.
> The problem is by example: if you update the price unit of the delivery line of the sale order, when you re-compute the delivery line, the custom price will be lost.
> 
> The original problem of this provides from the module `sale_coupon_advanced` which implied this new behavior for all sale order lines.
> With code core only, if you change the price unit of a sale order line, the custom price unit is kept even if you recompute coupon lines.
> With `sale_coupon_advanced`, it's not the case.
> That's why you must do this bridge.
> 
> Finally, for our needs, it's ok like you did, but it's a deep change of the original behavior.
> 
> Please add in the readme of the module `sale_coupon_advanced` that it's a limitation of the module which implied to lost custom price unit when we recompute coupon lines.
> 
> And please add in the readme of the module `sale_coupon_advanced_delivery` that the delivery line will be re-compute each time we recompute coupon lines.

Yes, we already discussed this with Emeric and Iryna and decided to go like this for now.
I will update readme to make it more clear (original issue comes from the fact that all order lines prices are recomputed each time promotion recompute is triggered -> which was done to reset prices if promotion pricelist was changed/removed. But if there was no such case, it is still reset, because you dont know if it was set before or not).

Also regarding `sale_coupon_advanced_delivery` its kind of limitation/feature, because yes you can't have custom price, but usually with delivery you want price to be computed from carrier (not set custom price). So in that case it improves, because it updates shipping price correctly (where original does nothing) -> I mean, if let say you get free shipping if you buy over 100 EUR, then recomputing promotions makes your order total amount less than 100 EUR -> meaning free shipping is no longer applicable. So it then updates shipping to be no longer free (or free in opposite case).

**Review by jcoux — APPROVED** [review]
Thanks for changes.

**Comment by oerp-odoo** [comment]
@jcoux can I merge? Same changes were already approved on that last PR

**Comment by jcoux** [comment]
@oerp-odoo For me yes you have only approved now.

**Comment by jcoux** [comment]
I merge it as original PR have been approved by other people.

**Pull request merged**
